apiVersion: v1
kind: ConfigMap
metadata:
  name: itinerary-config
  namespace: itinerary
data:
  Jwt__Issuer: "itinerary-be"
  Jwt__Audience: "itinerary-be-client"
  Google__RedirectUri: "http://localhost:3000"
